-- 2018 NCAA Men's Basketball Tournament - No games played

INSERT INTO teams(name, seed, season_wins, season_losses, current_winnings, still_alive) VALUES ('UVA', 1, 31, 2, 0, FALSE);
INSERT INTO teams(name, seed, season_wins, season_losses, current_winnings, still_alive) VALUES ('Villanova', 1, 30, 4, 0, TRUE);
INSERT INTO teams(name, seed, season_wins, season_losses, current_winnings, still_alive) VALUES ('Kansas', 1, 27, 7, .0, TRUE);
INSERT INTO teams(name, seed, season_wins, season_losses, current_winnings, still_alive) VALUES ('Xavier', 1, 28, 5, .0, FALSE);
INSERT INTO teams(name, seed, season_wins, season_losses, current_winnings, still_alive) VALUES ('Cincinnati', 2, 30, 4, .0, FALSE);
INSERT INTO teams(name, seed, season_wins, season_losses, current_winnings, still_alive) VALUES ('Purdue', 2, 28, 6, .0, TRUE);
INSERT INTO teams(name, seed, season_wins, season_losses, current_winnings, still_alive) VALUES ('Duke', 2, 26, 7, 0, TRUE);
INSERT INTO teams(name, seed, season_wins, season_losses, current_winnings, still_alive) VALUES ('UNC', 2, 25, 10, .0, FALSE);
INSERT INTO teams(name, seed, season_wins, season_losses, current_winnings, still_alive) VALUES ('Tennessee', 3, 25, 8, .0, FALSE);
INSERT INTO teams(name, seed, season_wins, season_losses, current_winnings, still_alive) VALUES ('Texas Tech', 3, 24, 9, .0, TRUE);
INSERT INTO teams(name, seed, season_wins, season_losses, current_winnings, still_alive) VALUES ('Michigan State', 3, 29, 4, .0, FALSE);
INSERT INTO teams(name, seed, season_wins, season_losses, current_winnings, still_alive) VALUES ('Michigan', 3, 28, 7, .0, TRUE);
INSERT INTO teams(name, seed, season_wins, season_losses, current_winnings, still_alive) VALUES ('Arizona', 4, 27, 7, .0, FALSE);
INSERT INTO teams(name, seed, season_wins, season_losses, current_winnings, still_alive) VALUES ('Wichita State', 4, 25, 7, .0, FALSE);
INSERT INTO teams(name, seed, season_wins, season_losses, current_winnings, still_alive) VALUES ('Auburn', 4, 25, 7, .0, FALSE);
INSERT INTO teams(name, seed, season_wins, season_losses, current_winnings, still_alive) VALUES ('Gonzaga', 4, 30, 4, .0, TRUE);
INSERT INTO teams(name, seed, season_wins, season_losses, current_winnings, still_alive) VALUES ('Kentucky', 5, 24, 10, .0, TRUE);
INSERT INTO teams(name, seed, season_wins, season_losses, current_winnings, still_alive) VALUES ('West Virginia', 5, 24, 10, .0, TRUE);
INSERT INTO teams(name, seed, season_wins, season_losses, current_winnings, still_alive) VALUES ('Clemson', 5, 23, 9, .0, TRUE);
INSERT INTO teams(name, seed, season_wins, season_losses, current_winnings, still_alive) VALUES ('Ohio State', 5, 24, 8, 0, FALSE);
INSERT INTO teams(name, seed, season_wins, season_losses, current_winnings, still_alive) VALUES ('Miami', 6, 22, 9, 0, FALSE);
INSERT INTO teams(name, seed, season_wins, season_losses, current_winnings, still_alive) VALUES ('Florida', 6, 20, 12, 0, FALSE);
INSERT INTO teams(name, seed, season_wins, season_losses, current_winnings, still_alive) VALUES ('TCU', 6, 21, 11, 0, FALSE);
INSERT INTO teams(name, seed, season_wins, season_losses, current_winnings, still_alive) VALUES ('Houston', 6, 26, 7, .0, FALSE);
INSERT INTO teams(name, seed, season_wins, season_losses, current_winnings, still_alive) VALUES ('Nevada', 7, 27, 7, .0, TRUE);
INSERT INTO teams(name, seed, season_wins, season_losses, current_winnings, still_alive) VALUES ('Arkansas', 7, 23, 11, .0, FALSE);
INSERT INTO teams(name, seed, season_wins, season_losses, current_winnings, still_alive) VALUES ('Rhode Island', 7, 25, 7, .0, FALSE);
INSERT INTO teams(name, seed, season_wins, season_losses, current_winnings, still_alive) VALUES ('Texas A&M', 7, 20, 12, 0, TRUE);
INSERT INTO teams(name, seed, season_wins, season_losses, current_winnings, still_alive) VALUES ('Creighton', 8, 21, 11, .0, FALSE);
INSERT INTO teams(name, seed, season_wins, season_losses, current_winnings, still_alive) VALUES ('Virginia Tech', 8, 21, 11, .0, FALSE);
INSERT INTO teams(name, seed, season_wins, season_losses, current_winnings, still_alive) VALUES ('Seton Hall', 8, 21, 11, 0, FALSE);
INSERT INTO teams(name, seed, season_wins, season_losses, current_winnings, still_alive) VALUES ('Missouri', 8, 20, 12, .0, FALSE);
INSERT INTO teams(name, seed, season_wins, season_losses, current_winnings, still_alive) VALUES ('Kansas State', 9, 22, 11, 0, TRUE);
INSERT INTO teams(name, seed, season_wins, season_losses, current_winnings, still_alive) VALUES ('Alabama', 9, 19, 15, 0, FALSE);
INSERT INTO teams(name, seed, season_wins, season_losses, current_winnings, still_alive) VALUES ('NC State', 9, 21, 11, .0, FALSE);
INSERT INTO teams(name, seed, season_wins, season_losses, current_winnings, still_alive) VALUES ('Florida State', 9, 20, 11, 0, TRUE);
INSERT INTO teams(name, seed, season_wins, season_losses, current_winnings, still_alive) VALUES ('Texas', 10, 19, 14, 0, FALSE);
INSERT INTO teams(name, seed, season_wins, season_losses, current_winnings, still_alive) VALUES ('Butler', 10, 20, 13, 0, FALSE);
INSERT INTO teams(name, seed, season_wins, season_losses, current_winnings, still_alive) VALUES ('Oklahoma', 10, 18, 13, 0, TRUE);
INSERT INTO teams(name, seed, season_wins, season_losses, current_winnings, still_alive) VALUES ('Providence', 10, 21, 13, .0, FALSE);
INSERT INTO teams(name, seed, season_wins, season_losses, current_winnings, still_alive) VALUES ('Loyola Chicago', 11, 28, 5, .0, TRUE);
INSERT INTO teams(name, seed, season_wins, season_losses, current_winnings, still_alive) VALUES ('St. Bonaventure', 11, 0, 0, .0, FALSE);
INSERT INTO teams(name, seed, season_wins, season_losses, current_winnings, still_alive) VALUES ('Syracuse', 11, 0, 0, .0, FALSE);
INSERT INTO teams(name, seed, season_wins, season_losses, current_winnings, still_alive) VALUES ('San Diego St.', 11, 22, 10, 0, FALSE);
INSERT INTO teams(name, seed, season_wins, season_losses, current_winnings, still_alive) VALUES ('Davidson', 12, 21, 11, 0, FALSE);
INSERT INTO teams(name, seed, season_wins, season_losses, current_winnings, still_alive) VALUES ('Murray St.', 12, 26, 5, 0, FALSE);
INSERT INTO teams(name, seed, season_wins, season_losses, current_winnings, still_alive) VALUES ('New Mexico St.', 12, 28, 5, 0, FALSE);
INSERT INTO teams(name, seed, season_wins, season_losses, current_winnings, still_alive) VALUES ('South Dakota St.', 12, 28, 6, .0, FALSE);
INSERT INTO teams(name, seed, season_wins, season_losses, current_winnings, still_alive) VALUES ('Buffalo', 13, 26, 8, 0, FALSE);
INSERT INTO teams(name, seed, season_wins, season_losses, current_winnings, still_alive) VALUES ('Marshall', 13, 24, 10, 0, FALSE);
INSERT INTO teams(name, seed, season_wins, season_losses, current_winnings, still_alive) VALUES ('Charleston', 13, 26, 7, 0, FALSE);
INSERT INTO teams(name, seed, season_wins, season_losses, current_winnings, still_alive) VALUES ('UNCG', 13, 27, 7, 0, FALSE);
INSERT INTO teams(name, seed, season_wins, season_losses, current_winnings, still_alive) VALUES ('Wright St.', 14, 25, 9, 0, FALSE);
INSERT INTO teams(name, seed, season_wins, season_losses, current_winnings, still_alive) VALUES ('S.F. Austin', 14, 28, 6, 0, FALSE);
INSERT INTO teams(name, seed, season_wins, season_losses, current_winnings, still_alive) VALUES ('Bucknell', 14, 25, 9, 0, FALSE);
INSERT INTO teams(name, seed, season_wins, season_losses, current_winnings, still_alive) VALUES ('Montana', 14, 26, 7, 0, FALSE);
INSERT INTO teams(name, seed, season_wins, season_losses, current_winnings, still_alive) VALUES ('Georgia St.', 15, 24, 10, 0, FALSE);
INSERT INTO teams(name, seed, season_wins, season_losses, current_winnings, still_alive) VALUES ('CSU Fullerton', 15, 20, 11, 0, FALSE);
INSERT INTO teams(name, seed, season_wins, season_losses, current_winnings, still_alive) VALUES ('Iona', 15, 20, 13, 0, FALSE);
INSERT INTO teams(name, seed, season_wins, season_losses, current_winnings, still_alive) VALUES ('Lipscomb', 15, 23, 9, 0, FALSE);
INSERT INTO teams(name, seed, season_wins, season_losses, current_winnings, still_alive) VALUES ('UMBC', 16, 24, 10, 0, FALSE);
INSERT INTO teams(name, seed, season_wins, season_losses, current_winnings, still_alive) VALUES ('Radford', 16, 0, 0, 0, FALSE);
INSERT INTO teams(name, seed, season_wins, season_losses, current_winnings, still_alive) VALUES ('Penn', 16, 24, 8, 0, FALSE);
INSERT INTO teams(name, seed, season_wins, season_losses, current_winnings, still_alive) VALUES ('Texas Southern', 16, 0, 0, 0, FALSE);
