-- 2017 NCAA Men's Basketball Tournament

INSERT INTO teams(name, seed, season_wins, season_losses, current_winnings, still_alive) VALUES ('Villanova', 1, 22, 3, .01, TRUE);
INSERT INTO teams(name, seed, season_wins, season_losses, current_winnings, still_alive) VALUES ('Gonzaga', 1, 29, 12, .12, TRUE);
INSERT INTO teams(name, seed, season_wins, season_losses, current_winnings, still_alive) VALUES ('Kansas', 1, 16, 14, .05, TRUE);
INSERT INTO teams(name, seed, season_wins, season_losses, current_winnings, still_alive) VALUES ('UNC', 1, 14, 3, .16, TRUE);
INSERT INTO teams(name, seed, season_wins, season_losses, current_winnings, still_alive) VALUES ('Duke', 2, 12, 14, .01, TRUE);
INSERT INTO teams(name, seed, season_wins, season_losses, current_winnings, still_alive) VALUES ('Arizona', 2, 22, 12, .025, TRUE);
INSERT INTO teams(name, seed, season_wins, season_losses, current_winnings, still_alive) VALUES ('Louisville', 2, 23, .01, 0, TRUE);
INSERT INTO teams(name, seed, season_wins, season_losses, current_winnings, still_alive) VALUES ('Kentucky', 2, 14, 8, .05, TRUE);
INSERT INTO teams(name, seed, season_wins, season_losses, current_winnings, still_alive) VALUES ('Baylor', 3, 20, 15, .025, TRUE);
INSERT INTO teams(name, seed, season_wins, season_losses, current_winnings, still_alive) VALUES ('Florida State', 3, 29, 15, .01, TRUE);
INSERT INTO teams(name, seed, season_wins, season_losses, current_winnings, still_alive) VALUES ('Oregon', 3, 21, 9, .08, TRUE);
INSERT INTO teams(name, seed, season_wins, season_losses, current_winnings, still_alive) VALUES ('UCLA', 3, 13, 6, .025, TRUE);
INSERT INTO teams(name, seed, season_wins, season_losses, current_winnings, still_alive) VALUES ('Florida', 4, 12, 14, .05, TRUE);
INSERT INTO teams(name, seed, season_wins, season_losses, current_winnings, still_alive) VALUES ('West Virginia', 4, 18, 10, .025, TRUE);
INSERT INTO teams(name, seed, season_wins, season_losses, current_winnings, still_alive) VALUES ('Purdue', 4, 15, 5, .025, TRUE);
INSERT INTO teams(name, seed, season_wins, season_losses, current_winnings, still_alive) VALUES ('Butler', 4, 26, 4, .025, TRUE);
INSERT INTO teams(name, seed, season_wins, season_losses, current_winnings, still_alive) VALUES ('UVA', 5, 15, 12, .01, TRUE);
INSERT INTO teams(name, seed, season_wins, season_losses, current_winnings, still_alive) VALUES ('Notre Dame', 5, 26, 11, .01, TRUE);
INSERT INTO teams(name, seed, season_wins, season_losses, current_winnings, still_alive) VALUES ('Iowa State', 5, 28, 7, .01, TRUE);
INSERT INTO teams(name, seed, season_wins, season_losses, current_winnings, still_alive) VALUES ('Minnesota', 5, 16, 6, 0, TRUE);
INSERT INTO teams(name, seed, season_wins, season_losses, current_winnings, still_alive) VALUES ('SMU', 6, 30, 14, 0, TRUE);
INSERT INTO teams(name, seed, season_wins, season_losses, current_winnings, still_alive) VALUES ('Maryland', 6, 21, 12, 0, TRUE);
INSERT INTO teams(name, seed, season_wins, season_losses, current_winnings, still_alive) VALUES ('Creighton', 6, 14, 9, 0, TRUE);
INSERT INTO teams(name, seed, season_wins, season_losses, current_winnings, still_alive) VALUES ('Cincinnati', 6, 24, 11, .01, TRUE);
INSERT INTO teams(name, seed, season_wins, season_losses, current_winnings, still_alive) VALUES ('South Carolina', 7, 26, 8, .08, TRUE);
INSERT INTO teams(name, seed, season_wins, season_losses, current_winnings, still_alive) VALUES ('Saint Mary"s', 7, 23, 13, .01, TRUE);
INSERT INTO teams(name, seed, season_wins, season_losses, current_winnings, still_alive) VALUES ('Michigan', 7, 10, 15, .025, TRUE);
INSERT INTO teams(name, seed, season_wins, season_losses, current_winnings, still_alive) VALUES ('Dayton', 7, 17, 5, 0, TRUE);
INSERT INTO teams(name, seed, season_wins, season_losses, current_winnings, still_alive) VALUES ('Wisconsin', 8, 27, 10, .025, TRUE);
INSERT INTO teams(name, seed, season_wins, season_losses, current_winnings, still_alive) VALUES ('Northwestern', 8, 23, 11, .01, TRUE);
INSERT INTO teams(name, seed, season_wins, season_losses, current_winnings, still_alive) VALUES ('Miami', 8, 13, 3, 0, TRUE);
INSERT INTO teams(name, seed, season_wins, season_losses, current_winnings, still_alive) VALUES ('Arkansas', 8, 30, 3, .01, TRUE);
INSERT INTO teams(name, seed, season_wins, season_losses, current_winnings, still_alive) VALUES ('Virginia Tech', 9, 25, 6, 0, TRUE);
INSERT INTO teams(name, seed, season_wins, season_losses, current_winnings, still_alive) VALUES ('Vanderbilt', 9, 23, 3, 0, TRUE);
INSERT INTO teams(name, seed, season_wins, season_losses, current_winnings, still_alive) VALUES ('Michigan State', 9, 18, 14, .01, TRUE);
INSERT INTO teams(name, seed, season_wins, season_losses, current_winnings, still_alive) VALUES ('Seton Hall', 9, 27, 3, 0, TRUE);
INSERT INTO teams(name, seed, season_wins, season_losses, current_winnings, still_alive) VALUES ('Marquette', 10, 17, 8, 0, TRUE);
INSERT INTO teams(name, seed, season_wins, season_losses, current_winnings, still_alive) VALUES ('VCU', 10, 16, 13, 0, TRUE);
INSERT INTO teams(name, seed, season_wins, season_losses, current_winnings, still_alive) VALUES ('Oklahoma State', 10, 26, 10, 0, TRUE);
INSERT INTO teams(name, seed, season_wins, season_losses, current_winnings, still_alive) VALUES ('Wichita State', 10, 26, 13, .01, TRUE);
INSERT INTO teams(name, seed, season_wins, season_losses, current_winnings, still_alive) VALUES ('USC/Providence', 11, 20, 8, .01, TRUE);
INSERT INTO teams(name, seed, season_wins, season_losses, current_winnings, still_alive) VALUES ('Xavier', 11, 26, 10, .05, TRUE);
INSERT INTO teams(name, seed, season_wins, season_losses, current_winnings, still_alive) VALUES ('URI', 11, 16, 5, .01, TRUE);
INSERT INTO teams(name, seed, season_wins, season_losses, current_winnings, still_alive) VALUES ('Kansas State/Wake Forest', 11, 29, 4, 0, TRUE);
INSERT INTO teams(name, seed, season_wins, season_losses, current_winnings, still_alive) VALUES ('UNC Wilmington', 12, 24, 9, 0, TRUE);
INSERT INTO teams(name, seed, season_wins, season_losses, current_winnings, still_alive) VALUES ('Princeton', 12, 12, 4, 0, TRUE);
INSERT INTO teams(name, seed, season_wins, season_losses, current_winnings, still_alive) VALUES ('Nevada', 12, 20, 12, 0, TRUE);
INSERT INTO teams(name, seed, season_wins, season_losses, current_winnings, still_alive) VALUES ('Mid Tennessee', 12, 29, 13, .01, TRUE);
INSERT INTO teams(name, seed, season_wins, season_losses, current_winnings, still_alive) VALUES ('ETSU', 13, 13, 3, 0, TRUE);
INSERT INTO teams(name, seed, season_wins, season_losses, current_winnings, still_alive) VALUES ('Bucknell', 13, 17, 13, 0, TRUE);
INSERT INTO teams(name, seed, season_wins, season_losses, current_winnings, still_alive) VALUES ('Vermont', 13, 10, 4, 0, TRUE);
INSERT INTO teams(name, seed, season_wins, season_losses, current_winnings, still_alive) VALUES ('Winthrop', 13, 23, 3, 0, TRUE);
INSERT INTO teams(name, seed, season_wins, season_losses, current_winnings, still_alive) VALUES ('New Mexico St', 14, 26, 14, 0, TRUE);
INSERT INTO teams(name, seed, season_wins, season_losses, current_winnings, still_alive) VALUES ('FGCU', 14, 23, 6, 0, TRUE);
INSERT INTO teams(name, seed, season_wins, season_losses, current_winnings, still_alive) VALUES ('Iona', 14, 17, 12, 0, TRUE);
INSERT INTO teams(name, seed, season_wins, season_losses, current_winnings, still_alive) VALUES ('Kent State', 14, 30, 7, 0, TRUE);
INSERT INTO teams(name, seed, season_wins, season_losses, current_winnings, still_alive) VALUES ('Troy', 15, 21, 13, 0, TRUE);
INSERT INTO teams(name, seed, season_wins, season_losses, current_winnings, still_alive) VALUES ('North Dakota', 15, 18, 8, 0, TRUE);
INSERT INTO teams(name, seed, season_wins, season_losses, current_winnings, still_alive) VALUES ('Jacksonville St', 15, 15, 10, 0, TRUE);
INSERT INTO teams(name, seed, season_wins, season_losses, current_winnings, still_alive) VALUES ('Mt. St. Mary/New Orleans', 16, 14, 11, 0, TRUE);
INSERT INTO teams(name, seed, season_wins, season_losses, current_winnings, still_alive) VALUES ('South Dakota St', 16, 13, 15, 0, TRUE);
INSERT INTO teams(name, seed, season_wins, season_losses, current_winnings, still_alive) VALUES ('UC Davis/NC Central', 16, 18, 9, 0, TRUE);
INSERT INTO teams(name, seed, season_wins, season_losses, current_winnings, still_alive) VALUES ('Texas Southern', 16, 28, 14, 0, TRUE);
INSERT INTO teams(name, seed, season_wins, season_losses, current_winnings, still_alive) VALUES ('Northern Kentucky', 15, 12, 10, 0, TRUE);
